'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const {createCreatorStore}=require('../scoped-store');
const {buildServer}=require('../server');

function fixture(){return{brief:{id:'brief-1',topic:'Agent observability',status:'evidence-ready',mode:'analysis',trigger:'release',audience:'data architects',teachingOutcome:'Understand the trade-off',creatorTake:'Observability should be designed before rollout.',platforms:['linkedin','medium']},sources:[{id:'source-1',url:'https://example.com/video',canonicalUrl:'https://example.com/video',evidenceClass:'first-party-public',title:'Launch',publisher:'Example',resolutionStatus:'resolved',sourceLocator:{kind:'transcript',startSeconds:42,endSeconds:55,passage:'qualified source passage'}}],claims:[{id:'claim-1',text:'The feature is generally available.',claimType:'fact',status:'supported',confidence:'high',supportingSourceIds:['source-1'],caveat:''}]}}

test('bundle survives close and reopen with source locator identity',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'creator-data-')),dbPath=path.join(dir,'creator.sqlite');let store=createCreatorStore({dbPath});const saved=store.saveBundle(fixture());assert.match(saved.receipt.hash,/^[a-f0-9]{64}$/);store.close();store=createCreatorStore({dbPath});const loaded=store.getBundle('brief-1');assert.equal(loaded.brief.id,'brief-1');assert.equal(loaded.sources[0].id,'source-1');assert.deepEqual(loaded.sources[0].sourceLocator,{kind:'transcript',startSeconds:42,endSeconds:55,passage:'qualified source passage'});assert.deepEqual(loaded.claims[0].supportingSourceIds,['source-1']);store.close();fs.rmSync(dir,{recursive:true,force:true})});

test('failed bundle update rolls back prior state',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'creator-data-')),dbPath=path.join(dir,'creator.sqlite'),store=createCreatorStore({dbPath});store.saveBundle(fixture());const bad=fixture();bad.brief={...bad.brief,topic:'Should roll back'};bad.sources=[bad.sources[0],{...bad.sources[0],id:'source-2'}];assert.throws(()=>store.saveBundle(bad));assert.equal(store.getBundle('brief-1').brief.topic,'Agent observability');assert.equal(store.getBundle('brief-1').sources.length,1);store.close();fs.rmSync(dir,{recursive:true,force:true})});

test('same logical source and claim ids remain isolated across briefs',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'creator-data-')),dbPath=path.join(dir,'creator.sqlite'),store=createCreatorStore({dbPath});const a=fixture();a.brief={...a.brief,id:'brief-a',topic:'Brief A'};a.sources=[{...a.sources[0],id:'shared-source',title:'Source in A'}];a.claims=[{...a.claims[0],id:'shared-claim',supportingSourceIds:['shared-source'],text:'Claim in A'}];const b=fixture();b.brief={...b.brief,id:'brief-b',topic:'Brief B'};b.sources=[{...b.sources[0],id:'shared-source',title:'Source in B',sourceLocator:{kind:'transcript',startSeconds:99,endSeconds:111,passage:'second brief passage'}}];b.claims=[{...b.claims[0],id:'shared-claim',supportingSourceIds:['shared-source'],text:'Claim in B'}];store.saveBundle(a);store.saveBundle(b);const loadedA=store.getBundle('brief-a'),loadedB=store.getBundle('brief-b');assert.equal(store.health().briefCount,2);assert.equal(loadedA.sources[0].id,'shared-source');assert.equal(loadedB.sources[0].id,'shared-source');assert.equal(loadedA.sources[0].title,'Source in A');assert.equal(loadedB.sources[0].title,'Source in B');assert.equal(loadedA.sources[0].sourceLocator.startSeconds,42);assert.equal(loadedB.sources[0].sourceLocator.startSeconds,99);assert.equal(loadedA.claims[0].id,'shared-claim');assert.equal(loadedB.claims[0].id,'shared-claim');assert.deepEqual(loadedA.claims[0].supportingSourceIds,['shared-source']);assert.deepEqual(loadedB.claims[0].supportingSourceIds,['shared-source']);store.close();fs.rmSync(dir,{recursive:true,force:true})});

test('http api requires bearer token and round-trips bundle',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'creator-data-')),dbPath=path.join(dir,'creator.sqlite'),oldToken=process.env.CREATOR_DATA_TOKEN;process.env.CREATOR_DATA_TOKEN='test-secret';const{server,store}=buildServer({dbPath});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const port=server.address().port,base=`http://127.0.0.1:${port}`;try{assert.equal((await fetch(`${base}/health`)).status,200);assert.equal((await fetch(`${base}/v1/briefs/brief-1`)).status,401);const put=await fetch(`${base}/v1/briefs/brief-1`,{method:'PUT',headers:{Authorization:'Bearer test-secret','Content-Type':'application/json'},body:JSON.stringify(fixture())});assert.equal(put.status,200);const get=await fetch(`${base}/v1/briefs/brief-1`,{headers:{Authorization:'Bearer test-secret'}});assert.equal(get.status,200);const body=await get.json();assert.equal(body.data.brief.id,'brief-1');assert.equal(body.data.sources[0].id,'source-1');assert.equal(body.data.sources[0].sourceLocator.startSeconds,42)}finally{await new Promise(resolve=>server.close(resolve));store.close();if(oldToken===undefined)delete process.env.CREATOR_DATA_TOKEN;else process.env.CREATOR_DATA_TOKEN=oldToken;fs.rmSync(dir,{recursive:true,force:true})}});
