'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const {buildServer}=require('../server');

function tempDb(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'creator-data-http-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));return path.join(dir,'creator.sqlite')}
async function start(dbPath){const instance=buildServer({dbPath});await new Promise((resolve,reject)=>{instance.server.once('error',reject);instance.server.listen(0,'127.0.0.1',resolve)});const address=instance.server.address();return{...instance,base:`http://127.0.0.1:${address.port}`}}
async function stop(instance){await new Promise(resolve=>instance.server.close(resolve));instance.store.close()}
async function json(url,init={}){const response=await fetch(url,init);const body=await response.json();return{response,body}}
const auth={'Authorization':'Bearer test-token','Content-Type':'application/json'};

test('health is public while data routes fail closed without bearer token',async t=>{const old=process.env.CREATOR_DATA_TOKEN;process.env.CREATOR_DATA_TOKEN='test-token';t.after(()=>{if(old===undefined)delete process.env.CREATOR_DATA_TOKEN;else process.env.CREATOR_DATA_TOKEN=old});const app=await start(tempDb(t));t.after(()=>stop(app));let result=await json(`${app.base}/health`);assert.equal(result.response.status,200);assert.equal(result.body.provider,'creator-sqlite');result=await json(`${app.base}/v1/profile`);assert.equal(result.response.status,401);assert.equal(result.body.code,'UNAUTHORIZED');result=await json(`${app.base}/v1/profile`,{headers:{Authorization:'Bearer wrong'}});assert.equal(result.response.status,401)});

test('brief API persists an atomic bundle and rejects path/body identity mismatch',async t=>{const old=process.env.CREATOR_DATA_TOKEN;process.env.CREATOR_DATA_TOKEN='test-token';t.after(()=>{if(old===undefined)delete process.env.CREATOR_DATA_TOKEN;else process.env.CREATOR_DATA_TOKEN=old});const app=await start(tempDb(t));t.after(()=>stop(app));const bundle={brief:{id:'brief-http',topic:'Evidence-first RAG',status:'evidence-ready',mode:'analysis',teachingOutcome:'Explain the trade-off',creatorTake:'Evaluation should be part of the architecture.'},sources:[{id:'source-http',url:'https://example.com/release',canonicalUrl:'https://example.com/release',evidenceClass:'official-doc',resolutionStatus:'resolved',sourceLocator:{type:'timestamp',startSeconds:12,endSeconds:26}}],claims:[{id:'claim-http',text:'The feature is generally available.',claimType:'fact',status:'supported',confidence:'high',supportingSourceIds:['source-http']}]};let result=await json(`${app.base}/v1/briefs/brief-http`,{method:'PUT',headers:auth,body:JSON.stringify(bundle)});assert.equal(result.response.status,200);assert.equal(result.body.data.brief.id,'brief-http');assert.equal(result.body.data.sources[0].sourceLocator.startSeconds,12);assert.match(result.body.receipt.hash,/^[a-f0-9]{64}$/);result=await json(`${app.base}/v1/briefs/brief-http`,{headers:auth});assert.equal(result.response.status,200);assert.equal(result.body.data.claims[0].supportingSourceIds[0],'source-http');result=await json(`${app.base}/v1/briefs/brief-http`,{method:'PUT',headers:auth,body:JSON.stringify({brief:{id:'different',topic:'Nope'}})});assert.equal(result.response.status,409);assert.equal(result.body.code,'BRIEF_ID_MISMATCH')});

test('profile research draft and publication APIs survive service restart',async t=>{const old=process.env.CREATOR_DATA_TOKEN;process.env.CREATOR_DATA_TOKEN='test-token';t.after(()=>{if(old===undefined)delete process.env.CREATOR_DATA_TOKEN;else process.env.CREATOR_DATA_TOKEN=old});const dbPath=tempDb(t);let app=await start(dbPath);let result=await json(`${app.base}/v1/profile`,{method:'PUT',headers:auth,body:JSON.stringify({identity:{displayName:'Test Creator'},voice:{tone:'technical'},expertise:['data-platforms']})});assert.equal(result.response.status,200);result=await json(`${app.base}/v1/research`,{method:'PUT',headers:auth,body:JSON.stringify({items:[{id:'research-http',sourceUrl:'https://example.com/docs',topic:'RAG evaluation',status:'primary-source-enriched'}]})});assert.equal(result.response.status,200);result=await json(`${app.base}/v1/drafts`,{method:'PUT',headers:auth,body:JSON.stringify({runId:'run-http',platform:'linkedin',topic:'RAG evaluation',content:'Draft body',version:1,status:'approved'})});assert.equal(result.response.status,200);result=await json(`${app.base}/v1/publications`,{method:'POST',headers:auth,body:JSON.stringify({runId:'run-http',platform:'linkedin',postId:'post-http',draftHash:'hash-http',receipt:{schema:'creator-publication-receipt/v1'}})});assert.equal(result.response.status,201);await stop(app);app=await start(dbPath);t.after(()=>stop(app));result=await json(`${app.base}/v1/profile`,{headers:auth});assert.equal(result.body.data.identity.displayName,'Test Creator');result=await json(`${app.base}/v1/research`,{headers:auth});assert.equal(result.body.data[0].id,'research-http');result=await json(`${app.base}/v1/drafts`,{headers:auth});assert.equal(result.body.data[0].runId,'run-http');result=await json(`${app.base}/v1/publications`,{headers:auth});assert.equal(result.body.data[0].externalId,'post-http')});
