'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const {createCreatorStore,receiptHash}=require('../store');
function fixture(id='brief-1'){return{brief:{id,topic:'Agent observability',status:'evidence-ready',mode:'analysis',trigger:'Official release',audience:'data and AI architects',teachingOutcome:'Understand the operational trade-offs',creatorTake:'Observability should be evaluated as an operating control, not a dashboard feature.',platforms:['linkedin','medium'],warnings:[]},sources:[{id:'source-1',url:'https://example.com/release',canonicalUrl:'https://example.com/release',evidenceClass:'official-doc',title:'Release note',publisher:'Example',resolutionStatus:'resolved',sourceLocator:{type:'timestamp',startSeconds:93,endSeconds:111,excerpt:'Observability is generally available.'}}],claims:[{id:'claim-1',text:'Observability is generally available.',claimType:'fact',status:'supported',confidence:'high',supportingSourceIds:['source-1'],caveat:''}]}}
function tempDb(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'creator-data-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));return path.join(dir,'creator.sqlite')}
test('save/reload survives close and reopen with identity intact',t=>{const dbPath=tempDb(t);const first=createCreatorStore({dbPath});const saved=first.saveBundle(fixture());assert.equal(saved.brief.id,'brief-1');assert.equal(saved.sources[0].id,'source-1');assert.equal(saved.claims[0].id,'claim-1');assert.equal(saved.sources[0].sourceLocator.startSeconds,93);assert.match(saved.receipt.hash,/^[a-f0-9]{64}$/);first.close();const second=createCreatorStore({dbPath});const recovered=second.getBundle('brief-1');assert.equal(recovered.brief.id,'brief-1');assert.deepEqual(recovered.claims[0].supportingSourceIds,['source-1']);assert.deepEqual(recovered.sources[0].sourceLocator,fixture().sources[0].sourceLocator);assert.equal(second.latestReceipt('brief-1').hash,saved.receipt.hash);second.close()});
test('bundle replacement removes stale sources and claims explicitly',t=>{const dbPath=tempDb(t);const store=createCreatorStore({dbPath});store.saveBundle(fixture());const replacement=fixture();replacement.sources=[];replacement.claims=[];replacement.brief.status='researching';store.saveBundle(replacement);const recovered=store.getBundle('brief-1');assert.equal(recovered.brief.status,'researching');assert.deepEqual(recovered.sources,[]);assert.deepEqual(recovered.claims,[]);store.close()});
test('transaction rolls back entire bundle on source uniqueness failure',t=>{const dbPath=tempDb(t);const store=createCreatorStore({dbPath});store.saveBundle(fixture());const broken=fixture();broken.brief.topic='This update must roll back';broken.sources=[{...fixture().sources[0],id:'source-a'},{...fixture().sources[0],id:'source-b'}];assert.throws(()=>store.saveBundle(broken));const recovered=store.getBundle('brief-1');assert.equal(recovered.brief.topic,'Agent observability');assert.equal(recovered.sources.length,1);assert.equal(recovered.sources[0].id,'source-1');store.close()});
test('receipts are deterministic for equivalent recovered bundles',t=>{const dbPath=tempDb(t);const store=createCreatorStore({dbPath});store.saveBundle(fixture());const bundle=store.getBundle('brief-1');assert.equal(receiptHash(bundle),receiptHash(JSON.parse(JSON.stringify(bundle))));store.close()});
