import type { TemplateDocument, TemplatePage } from '../template-engine/schema';
import type { CompiledWorkflowArtifacts, WorkflowStep } from './schema';

function pageForStep(step: WorkflowStep, total: number): TemplatePage {
  const evidenceLabel = step.evidenceRefs.length > 0
    ? `Evidence: ${step.evidenceRefs.join(', ')}`
    : 'Evidence: none attached';

  return {
    id: `workflow-${step.ordinal}`,
    name: `Step ${step.ordinal}`,
    canvas: {
      width: 1920,
      height: 1080,
      backgroundColor: '#0B0D10',
      backgroundImage: '',
      borderWidth: 0,
      borderColor: 'transparent',
      borderStyle: 'solid',
    },
    groups: [],
    elements: [
      {
        id: `accent-${step.ordinal}`,
        type: 'shape',
        name: 'Accent',
        shapeType: 'rectangle',
        position: { x: 0, y: 0 },
        dimensions: { width: 22, height: 1080 },
        rotation: 0,
        zIndex: 1,
        hidden: false,
        locked: true,
        parameterizable: false,
        style: { fill: '#D7FF64', stroke: 'transparent', strokeWidth: 0, borderRadius: 0, opacity: 1 },
      },
      {
        id: `step-number-${step.ordinal}`,
        type: 'text',
        name: 'Step number',
        content: `STEP ${step.ordinal} OF ${total}`,
        position: { x: 120, y: 90 },
        dimensions: { width: 760, height: 70 },
        rotation: 0,
        zIndex: 2,
        hidden: false,
        locked: true,
        parameterizable: false,
        style: {
          fontSize: 38,
          minFontSize: 24,
          fontFamily: 'Inter',
          fontWeight: 800,
          color: '#D7FF64',
          textAlign: 'left',
          verticalAlign: 'flex-start',
          letterSpacing: 1.4,
          lineHeight: 1.1,
          textMode: 'fit',
          opacity: 1,
          borderRadius: 0,
          textStrokeWidth: 0,
          textStrokeColor: '#000000',
        },
        repeatOnOverflow: false,
        flowBreakBehavior: 'line',
        flowMinLinesBeforeBreak: 2,
        flowMinLinesAfterBreak: 2,
      },
      {
        id: `title-${step.ordinal}`,
        type: 'text',
        name: 'Step title',
        content: step.title,
        position: { x: 120, y: 210 },
        dimensions: { width: 1540, height: 230 },
        rotation: 0,
        zIndex: 3,
        hidden: false,
        locked: true,
        parameterizable: false,
        style: {
          fontSize: 78,
          minFontSize: 44,
          fontFamily: 'Inter',
          fontWeight: 800,
          color: '#FFFFFF',
          textAlign: 'left',
          verticalAlign: 'flex-start',
          letterSpacing: -1,
          lineHeight: 1.05,
          textMode: 'fit',
          opacity: 1,
          borderRadius: 0,
          textStrokeWidth: 0,
          textStrokeColor: '#000000',
        },
        repeatOnOverflow: false,
        flowBreakBehavior: 'line',
        flowMinLinesBeforeBreak: 2,
        flowMinLinesAfterBreak: 2,
      },
      {
        id: `narration-${step.ordinal}`,
        type: 'text',
        name: 'Instruction',
        content: step.target ? `${step.narration}\nTarget: ${step.target}` : step.narration,
        position: { x: 120, y: 500 },
        dimensions: { width: 1540, height: 270 },
        rotation: 0,
        zIndex: 4,
        hidden: false,
        locked: true,
        parameterizable: false,
        style: {
          fontSize: 46,
          minFontSize: 28,
          fontFamily: 'Inter',
          fontWeight: 500,
          color: '#E8E9EB',
          textAlign: 'left',
          verticalAlign: 'flex-start',
          letterSpacing: 0,
          lineHeight: 1.2,
          textMode: 'fit',
          opacity: 1,
          borderRadius: 0,
          textStrokeWidth: 0,
          textStrokeColor: '#000000',
        },
        repeatOnOverflow: false,
        flowBreakBehavior: 'line',
        flowMinLinesBeforeBreak: 2,
        flowMinLinesAfterBreak: 2,
      },
      {
        id: `provenance-${step.ordinal}`,
        type: 'text',
        name: 'Provenance',
        content: `${evidenceLabel} • ${step.atMs}–${step.endMs} ms • ${step.reviewState}`,
        position: { x: 120, y: 940 },
        dimensions: { width: 1600, height: 55 },
        rotation: 0,
        zIndex: 5,
        hidden: false,
        locked: true,
        parameterizable: false,
        style: {
          fontSize: 24,
          minFontSize: 16,
          fontFamily: 'Inter',
          fontWeight: 500,
          color: '#8F969F',
          textAlign: 'left',
          verticalAlign: 'center',
          letterSpacing: 0,
          lineHeight: 1.1,
          textMode: 'truncate',
          opacity: 1,
          borderRadius: 0,
          textStrokeWidth: 0,
          textStrokeColor: '#000000',
        },
        repeatOnOverflow: false,
        flowBreakBehavior: 'line',
        flowMinLinesBeforeBreak: 2,
        flowMinLinesAfterBreak: 2,
      },
    ],
    audioTracks: [
      {
        id: `voice-${step.ordinal}`,
        label: `Step ${step.ordinal} narration`,
        tts: { text: step.narration, voiceId: 'en-us', modelId: 'local' },
        volume: 1,
        fadeIn: 0.05,
        fadeOut: 0.2,
        trimStart: 0,
        trimEnd: null,
        offset: 0,
        loop: false,
        muted: false,
        enabled: true,
      },
    ],
    subtitle: {
      source: 'auto-audio',
      enabled: true,
      fontSize: '38px',
      fontFamily: 'Inter, sans-serif',
      fontWeight: '700',
      color: '#FFFFFF',
      highlightColor: '#D7FF64',
      background: 'rgba(0,0,0,0.38)',
      position: 'bottom',
      offset: 96,
      mode: 'word-by-word',
      wordReveal: 'highlight',
      split: 'word',
      maxWordsPerLine: 6,
    },
    videoDuration: null,
  };
}

export function trainingTemplateFromWorkflow(artifacts: CompiledWorkflowArtifacts): TemplateDocument {
  const { graph, videoPlan } = artifacts;
  if (graph.revision.id !== videoPlan.sourceRevisionId) {
    throw new Error('video plan revision does not match workflow graph revision');
  }
  if (graph.steps.length === 0) {
    throw new Error('workflow must contain at least one step');
  }

  return {
    schemaVersion: 1,
    name: `Workflow Training — ${graph.revision.workflowId}`,
    description: `Generated from ${graph.revision.id}; capture ${graph.revision.captureId}. Each page preserves exact workflow-step provenance.`,
    tags: ['workflow-training', 're-375', graph.revision.workflowId, graph.revision.id],
    canvasWidth: 1920,
    canvasHeight: 1080,
    pages: graph.steps.map((step) => pageForStep(step, graph.steps.length)),
    variants: [],
  };
}
