import type { TemplateDocument } from './schema';

export const editorialShortTemplate: TemplateDocument = {
  schemaVersion: 1,
  name: 'Editorial Short',
  description: '9:16 faceless explainer with hook, narration, stat card and word-highlight subtitles.',
  tags: ['faceless', 'shorts', 'editorial', '9:16'],
  canvasWidth: 1080,
  canvasHeight: 1920,
  variants: [
    { id: 'square', name: 'Square', width: 1080, height: 1080, mode: 'auto' },
    { id: 'landscape', name: 'Landscape', width: 1920, height: 1080, mode: 'auto' },
  ],
  pages: [
    {
      id: 'page-editorial-main',
      name: 'Main',
      canvas: {
        width: 1080,
        height: 1920,
        backgroundColor: '#0B0D10',
        backgroundImage: '',
        borderWidth: 0,
        borderColor: 'transparent',
        borderStyle: 'solid',
      },
      groups: [
        { id: 'hero-copy', name: 'Hero copy' },
        { id: 'stat-card', name: 'Stat card' },
      ],
      elements: [
        {
          id: 'accent-top',
          type: 'shape',
          name: 'Top accent',
          shapeType: 'rectangle',
          position: { x: 0, y: 0 },
          dimensions: { width: 1080, height: 18 },
          rotation: 0,
          zIndex: 1,
          hidden: false,
          locked: false,
          parameterizable: true,
          parameterId: 'accent',
          style: { fill: '#D7FF64', stroke: 'transparent', strokeWidth: 0, borderRadius: 0, opacity: 1 },
        },
        {
          id: 'topic',
          type: 'text',
          name: 'Topic label',
          content: 'ARTIFICIAL INTELLIGENCE',
          position: { x: 90, y: 90 },
          dimensions: { width: 900, height: 48 },
          rotation: 0,
          zIndex: 2,
          hidden: false,
          locked: false,
          groupId: 'hero-copy',
          parameterizable: true,
          parameterId: 'topic',
          transitions: { showAt: 0, enterType: 'fade', enterDuration: 0.3, exitType: 'none', exitDuration: 0.4, easing: 'ease-out', ambient: 'none' },
          motion: { wake: { duration: 0.35, from: 'up', distance: 20, offset: 0 } },
          style: { fontSize: 30, minFontSize: 20, fontFamily: 'Inter', fontWeight: 800, color: '#D7FF64', textAlign: 'left', verticalAlign: 'flex-start', letterSpacing: 1.5, lineHeight: 1.1, textMode: 'fit', opacity: 1, borderRadius: 0, textStrokeWidth: 0, textStrokeColor: '#000000' },
          repeatOnOverflow: false,
          flowBreakBehavior: 'line',
          flowMinLinesBeforeBreak: 2,
          flowMinLinesAfterBreak: 2,
        },
        {
          id: 'hook',
          type: 'text',
          name: 'Hook',
          content: 'AI agents fail for a surprisingly human reason.',
          position: { x: 90, y: 220 },
          dimensions: { width: 900, height: 470 },
          rotation: 0,
          zIndex: 3,
          hidden: false,
          locked: false,
          groupId: 'hero-copy',
          parameterizable: true,
          parameterId: 'hook',
          motion: { reveal: { by: 'word', stagger: 0.065, duration: 0.7, dy: 80 } },
          style: { fontSize: 82, minFontSize: 48, fontFamily: 'Inter', fontWeight: 800, color: '#FFFFFF', textAlign: 'left', verticalAlign: 'flex-start', letterSpacing: -1.5, lineHeight: 1.02, textMode: 'fit', opacity: 1, backgroundColor: 'transparent', borderRadius: 0, textStrokeWidth: 0, textStrokeColor: '#000000' },
          repeatOnOverflow: false,
          flowBreakBehavior: 'line',
          flowMinLinesBeforeBreak: 2,
          flowMinLinesAfterBreak: 2,
        },
        {
          id: 'stat-bg',
          type: 'shape',
          name: 'Stat background',
          shapeType: 'rectangle',
          position: { x: 90, y: 760 },
          dimensions: { width: 900, height: 290 },
          rotation: 0,
          zIndex: 4,
          hidden: false,
          locked: false,
          groupId: 'stat-card',
          parameterizable: false,
          style: { fill: '#14181D', stroke: '#2B3037', strokeWidth: 2, borderRadius: 36, opacity: 1 },
          motion: { wake: { duration: 0.45, from: 'up', distance: 28, offset: 0.35 } },
        },
        {
          id: 'stat-number',
          type: 'text',
          name: 'Stat number',
          content: '3',
          position: { x: 145, y: 805 },
          dimensions: { width: 360, height: 135 },
          rotation: 0,
          zIndex: 5,
          hidden: false,
          locked: false,
          groupId: 'stat-card',
          parameterizable: true,
          parameterId: 'stat_number',
          style: { fontSize: 116, minFontSize: 60, fontFamily: 'Inter', fontWeight: 900, color: '#D7FF64', textAlign: 'left', verticalAlign: 'center', letterSpacing: -2, lineHeight: 1, textMode: 'fit', opacity: 1, borderRadius: 0, textStrokeWidth: 0, textStrokeColor: '#000000' },
          repeatOnOverflow: false,
          flowBreakBehavior: 'line',
          flowMinLinesBeforeBreak: 2,
          flowMinLinesAfterBreak: 2,
          motion: { count: { from: 0, to: 3, duration: 1.1, decimals: 0, prefix: '', suffix: '' }, after: { element: 'stat-bg', offset: 0.05 } },
        },
        {
          id: 'stat-label',
          type: 'text',
          name: 'Stat label',
          content: 'hearts in an octopus',
          position: { x: 145, y: 940 },
          dimensions: { width: 780, height: 68 },
          rotation: 0,
          zIndex: 6,
          hidden: false,
          locked: false,
          groupId: 'stat-card',
          parameterizable: true,
          parameterId: 'stat_label',
          style: { fontSize: 34, minFontSize: 24, fontFamily: 'Inter', fontWeight: 650, color: '#E8E9EB', textAlign: 'left', verticalAlign: 'center', letterSpacing: 0, lineHeight: 1.1, textMode: 'fit', opacity: 1, borderRadius: 0, textStrokeWidth: 0, textStrokeColor: '#000000' },
          repeatOnOverflow: false,
          flowBreakBehavior: 'line',
          flowMinLinesBeforeBreak: 2,
          flowMinLinesAfterBreak: 2,
          motion: { after: { element: 'stat-number', offset: 0.05 }, wake: { duration: 0.35, from: 'up', distance: 18, offset: 0 } },
        },
        {
          id: 'handle',
          type: 'text',
          name: 'Handle',
          content: '@faceless',
          position: { x: 90, y: 1780 },
          dimensions: { width: 600, height: 50 },
          rotation: 0,
          zIndex: 7,
          hidden: false,
          locked: false,
          parameterizable: true,
          parameterId: 'handle',
          style: { fontSize: 25, minFontSize: 20, fontFamily: 'Inter', fontWeight: 600, color: '#A2A7AF', textAlign: 'left', verticalAlign: 'center', letterSpacing: 0.2, lineHeight: 1, textMode: 'fit', opacity: 1, borderRadius: 0, textStrokeWidth: 0, textStrokeColor: '#000000' },
          repeatOnOverflow: false,
          flowBreakBehavior: 'line',
          flowMinLinesBeforeBreak: 2,
          flowMinLinesAfterBreak: 2,
        },
      ],
      audioTracks: [
        {
          id: 'narration',
          label: 'Narration',
          tts: { text: 'AI agents need more than a prompt. They need memory so they can keep state, recall decisions and improve from prior work.', voiceId: 'en-us', modelId: 'local', parameterId: 'voiceover' },
          volume: 1,
          fadeIn: 0.1,
          fadeOut: 0.25,
          trimStart: 0,
          trimEnd: null,
          offset: 0,
          loop: false,
          muted: false,
          enabled: true,
        },
      ],
      subtitle: {
        source: 'auto-audio',
        enabled: true,
        fontSize: '46px',
        fontFamily: 'Inter, sans-serif',
        fontWeight: '800',
        color: '#FFFFFF',
        highlightColor: '#D7FF64',
        background: 'rgba(0,0,0,0.34)',
        position: 'bottom',
        offset: 190,
        mode: 'word-by-word',
        wordReveal: 'highlight',
        split: 'word',
        maxWordsPerLine: 4,
      },
      videoDuration: null,
      motion: {
        look: { grain: 0.045, vignette: 0.24 },
        camera: { moves: [{ at: 2.4, duration: 1.5, x: 0, y: -10, zoom: 1.025, ease: 'ease-in-out' }] },
      },
    },
  ],
};

export const builtInTemplates = [editorialShortTemplate];
