'use strict';
const $=id=>document.getElementById(id);
const STATE={health:null,storage:null,feed:[],sources:[],selected:null,lastRun:null,approvals:null,profile:null,drafts:[]};
const readyStatus=x=>['primary-source-enriched','verified-seed'].includes(x?.status);
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function fmtDate(v){if(!v)return'undated';const d=new Date(`${v}T00:00:00Z`);return Number.isNaN(d.valueOf())?String(v):d.toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'})}
function setNotice(id,text,kind='warn'){const el=$(id);el.className=`notice ${kind}`;el.textContent=text}
function showView(name){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.querySelectorAll('[data-view]').forEach(b=>b.classList.remove('active'));$(`view-${name}`)?.classList.add('active');document.querySelector(`[data-view="${name}"]`)?.classList.add('active');$('topTitle').textContent=name==='today'?'Today':name[0].toUpperCase()+name.slice(1);if(name==='research')renderResearch();if(name==='library')loadLibrary();if(name==='runs')renderRuns();}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>showView(b.dataset.jump));document.querySelectorAll('[data-draft-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-draft-tab]').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.draftPane').forEach(x=>x.classList.add('hidden'));b.classList.add('active');$(`pane-${b.dataset.draftTab}`).classList.remove('hidden')});

function card(item,compact=false){const ready=readyStatus(item),date=item.publishedAt?fmtDate(item.publishedAt):'date pending',status=ready?'evidence ready':'needs evidence review';return `<article class="story"><div><div class="storyMeta"><span class="vendor">${esc(item.vendor)}</span><span>•</span><span>${esc(date)}</span><span class="badge ${ready?'good':'warn'}">${esc(status)}</span></div><h3>${esc(item.topic)}</h3><p>${esc(item.summary||'Primary source discovered. Evidence enrichment is pending.')}</p>${compact?'':`<p class="why"><b>Why it may be worth teaching:</b> ${esc(item.whyItMatters||'Matched your research universe and teaching criteria.')}</p>`}<div class="chips">${(item.categories||[]).map(c=>`<span class="chip">${esc(c)}</span>`).join('')}</div><div class="storyActions"><button class="btn choose" data-id="${esc(item.id)}">${ready?'Add my take':'Inspect evidence'}</button><button class="btn primary create" data-id="${esc(item.id)}" ${ready?'':'disabled'}>Create lesson</button><a class="btn ghost" href="${esc(item.sourceUrl)}" target="_blank" rel="noopener">Primary source ↗</a></div></div><div class="scoreBox"><div class="score">${Number(item.educationalPotential||0)}</div><small>educational potential</small><div class="meter"><div style="width:${Number(item.educationalPotential||0)}%"></div></div><div class="tiny">fit ${Number(item.signals?.fit||0)}/5 · evidence ${Number(item.signals?.evidence||0)}/5</div></div></article>`}
function bindCards(root){root.querySelectorAll('.choose,.create').forEach(b=>b.onclick=()=>selectItem(b.dataset.id,b.classList.contains('create')))}
function renderToday(){const root=$('todayFeed');root.innerHTML=STATE.feed.length?STATE.feed.map(x=>card(x)).join(''):'<div class="placeholder">No research items available.</div>';bindCards(root);$('readyCount').textContent=STATE.feed.length;$('evidenceCount').textContent=STATE.feed.filter(readyStatus).length;$('liveCount').textContent=STATE.feed.filter(x=>x.discovery?.mode!=='verified-seed').length;$('draftCount').textContent=STATE.drafts.length;$('publishedCount').textContent='0';renderSourceHealth();}
function renderSourceHealth(){const root=$('sourceHealth');if(!root)return;root.innerHTML=(STATE.sources||[]).map(s=>`<div class="sourceItem"><b>${esc(s.vendor)}</b><div>${s.ok?`online · ${esc(s.mode||'html')} · ${s.count} found`:`degraded · ${esc(s.error||'fetch failed')}`}</div><span class="badge ${s.ok?'good':'warn'}" style="margin-top:7px">${s.ok?'live':'fallback'}</span></div>`).join('')||'<div class="tiny">Source health unavailable.</div>'}
function renderResearch(){const q=($('researchFilter').value||'').toLowerCase();const list=STATE.feed.filter(x=>!q||`${x.vendor} ${x.topic} ${(x.categories||[]).join(' ')}`.toLowerCase().includes(q));const root=$('researchFeed');root.innerHTML=list.length?list.map(x=>card(x,true)).join(''):'<div class="placeholder">No matching items.</div>';bindCards(root);renderSourceHealth()}
$('researchFilter').oninput=renderResearch;

function selectItem(id,jump=true){STATE.selected=STATE.feed.find(x=>x.id===id)||null;if(!STATE.selected)return;const x=STATE.selected;$('composeTopic').value=x.topic;$('creatorTake').value='';$('angleSelect').innerHTML=(x.angleSuggestions||[]).map((a,i)=>`<option ${i===0?'selected':''}>${esc(a)}</option>`).join('')||'<option>Explain what changed and why it matters</option>';$('selectedEvidence').innerHTML=`<b>${esc(x.sourceTitle||x.topic)}</b><div class="tiny" style="margin:5px 0">${esc(x.vendor)} · ${esc(fmtDate(x.publishedAt))} · ${esc(x.status)}</div><a href="${esc(x.sourceUrl)}" target="_blank" rel="noopener">${esc(x.sourceUrl)}</a>`;$('packetSources').innerHTML=`<div class="sourceItem"><b>${esc(x.sourceTitle||x.topic)}</b><div>${esc(x.evidence?.sourceType||x.sourceType||'official-source')} · ${esc(x.evidence?.confidence||'medium')} confidence</div><div>${esc((x.evidence?.excerpt||x.summary||'').slice(0,500))}</div></div>`;$('evidenceBadge').className=`badge ${readyStatus(x)?'good':'warn'}`;$('evidenceBadge').textContent=readyStatus(x)?'primary evidence ready':'evidence review pending';$('buildLesson').disabled=!readyStatus(x);setNotice('composeStatus',readyStatus(x)?'Primary-source evidence is ready. Add your take and run the harness.':'This discovery has not completed primary-source enrichment yet. Open the source or wait for the next refresh before generation.',readyStatus(x)?'good':'warn');if(jump)showView('create')}

function contextProfile(){const p=STATE.profile||{};return{identity:{name:p.identity?.name||'',role:p.identity?.role||'Senior Data Architect / AI practitioner',bio:p.identity?.bio||'',audience:p.identity?.audience||'data engineers, architects and AI builders'},voice:{tone:p.voice?.tone||'technical, educational, concise, evidence-led',dos:p.voice?.dos||[],donts:p.voice?.donts||[]},expertise:p.expertise||[]}}
async function buildLesson(){const x=STATE.selected,topic=$('composeTopic').value.trim();if(!x||!readyStatus(x)){setNotice('composeStatus','Choose an evidence-ready research item first.','bad');return}if(!topic)return setNotice('composeStatus','Topic is required.','bad');const take=$('creatorTake').value.trim(),angle=$('angleSelect').value;const ev=x.evidence||{};const evidence=[{id:x.id,claim:x.summary||x.topic,excerpt:ev.excerpt||x.summary||x.whyItMatters,sourceUrl:x.sourceUrl,sourceType:ev.sourceType||x.sourceType||'official-blog',publishedAt:ev.publishedAt||x.publishedAt,confidence:ev.confidence||'high'}];const payload={topic,objective:[angle,take?`Creator perspective: ${take}`:''].filter(Boolean).join('\n'),platforms:['linkedin','medium'],freshness:'current',lane:'new-development',requirePrimarySources:true,minSources:1,maxRevisionLoops:1,evidence,context:contextProfile()};$('buildLesson').disabled=true;setNotice('composeStatus','Running evidence → context → writer → critic → revision…','warn');setEditor('linkedin','Working…',true);setEditor('medium','Working…',true);try{const r=await fetch('/api/harness',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),j=await r.json();if(!r.ok)throw new Error(j.message||j.error);STATE.lastRun=j;STATE.approvals=null;localStorage.setItem('creator-last-run',JSON.stringify(j.receipt||{}));if(j.status==='approval-required'){setEditor('linkedin',j.drafts.linkedin);setEditor('medium',j.drafts.medium);$('qualityBadge').className='badge good';$('qualityBadge').textContent='quality passed';setNotice('composeStatus','Both platform drafts passed quality gates and are waiting for your approval.','good');$('approveBoth').disabled=false;await persistRunDrafts(j,'draft')}else if(j.status==='blocked-model'){setEditor('linkedin','The research/evidence/context pipeline completed, but the writer is not connected. Complete the OpenAI API key setup and add the credential to the deployment.');setEditor('medium','BLOCKED_MODEL_NOT_CONFIGURED');$('qualityBadge').className='badge warn';$('qualityBadge').textContent='writer blocked';setNotice('composeStatus','Harness stopped truthfully at BLOCKED_MODEL_NOT_CONFIGURED.','warn')}else{setEditor('linkedin',JSON.stringify(j.quality||j.evidenceGate||j,null,2));setEditor('medium',`Run status: ${j.status}`);$('qualityBadge').className='badge bad';$('qualityBadge').textContent=j.status;setNotice('composeStatus',`Harness stopped at ${j.status}.`,'bad')}renderRuns()}catch(e){setNotice('composeStatus',`Run failed: ${e.message}`,'bad')}finally{$('buildLesson').disabled=!readyStatus(STATE.selected)}}
function setEditor(platform,text,empty=false){const el=$(`${platform}Draft`);el.textContent=text||'';el.classList.toggle('empty',Boolean(empty))}
$('buildLesson').onclick=buildLesson;

function localDrafts(){try{return JSON.parse(localStorage.getItem('creator-drafts')||'[]')}catch{return[]}}
function saveLocalDraft(row){const arr=localDrafts().filter(x=>!(x.runId===row.runId&&x.platform===row.platform&&x.version===row.version));arr.unshift({...row,createdAt:new Date().toISOString()});localStorage.setItem('creator-drafts',JSON.stringify(arr.slice(0,100)));STATE.drafts=arr.slice(0,100)}
async function persistRunDrafts(run,status,approvals=null){for(const platform of run.contract?.platforms||[]){const row={runId:run.runId,platform,topic:run.contract.topic,content:run.drafts[platform],status,version:1,runReceipt:run.receipt,approvalReceipt:approvals?.[platform]||null};if(STATE.storage?.configured){try{await fetch('/api/drafts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(row)})}catch{saveLocalDraft(row)}}else saveLocalDraft(row)}$('draftCount').textContent=STATE.storage?.configured?'server':STATE.drafts.length}
async function approveBoth(){const run=STATE.lastRun;if(!run?.receipt)return;try{$('approveBoth').disabled=true;const r=await fetch('/api/approve',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({runReceipt:run.receipt,drafts:run.drafts})}),j=await r.json();if(!r.ok)throw new Error(j.message||j.error);STATE.approvals=j.approvals;await persistRunDrafts(run,'approved',j.approvals);$('approveBoth').textContent='Approved ✓';$('publishLinkedIn').disabled=!STATE.health?.capabilities?.linkedinPublish;$('exportMedium').disabled=false;setNotice('composeStatus',STATE.health?.capabilities?.linkedinPublish?'Approved. LinkedIn publishing and Medium export are unlocked.':'Approved. Medium export is ready; LinkedIn publishing is waiting for account credentials.','good')}catch(e){$('approveBoth').disabled=false;setNotice('composeStatus',`Approval failed: ${e.message}`,'bad')}}
$('approveBoth').onclick=approveBoth;
async function publishLinkedIn(){if(!STATE.approvals?.linkedin||!STATE.lastRun)return;const draft=STATE.lastRun.drafts.linkedin;if(!confirm('Publish this exact approved LinkedIn post now?'))return;try{$('publishLinkedIn').disabled=true;setNotice('composeStatus','Publishing approved content directly to LinkedIn…','warn');const r=await fetch('/api/publish-linkedin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({draft,approval:STATE.approvals.linkedin})}),j=await r.json();if(!r.ok)throw new Error(j.message||j.error);setNotice('composeStatus',`Published to LinkedIn${j.postId?`: ${j.postId}`:''}.`,'good');$('publishLinkedIn').textContent='Published ✓'}catch(e){$('publishLinkedIn').disabled=false;setNotice('composeStatus',`LinkedIn publish failed: ${e.message}`,'bad')}}
$('publishLinkedIn').onclick=publishLinkedIn;
async function exportMedium(){if(!STATE.lastRun)return;try{const draft=STATE.lastRun.drafts.medium,r=await fetch('/api/export-medium',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:STATE.lastRun.contract.topic,draft})}),j=await r.json();if(!r.ok)throw new Error(j.message||j.error);const blob=new Blob([j.html],{type:'text/html'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${STATE.lastRun.contract.topic.replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'').toLowerCase()||'medium-article'}.html`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('composeStatus','Medium HTML export created. Import or paste it into Medium for publication.','good')}catch(e){setNotice('composeStatus',`Medium export failed: ${e.message}`,'bad')}}
$('exportMedium').onclick=exportMedium;

function renderManual(){const arr=manualItems();$('manualSaved').innerHTML=arr.length?arr.map(x=>`<div class="sourceItem"><b>${esc(x.url)}</b><div>${esc(x.take)}</div></div>`).join(''):'<span class="tiny">No manual research saved yet.</span>'}
function manualItems(){try{return JSON.parse(localStorage.getItem('creator-inbox')||'[]')}catch{return[]}}
$('manualSave').onclick=()=>{const url=$('manualUrl').value.trim(),take=$('manualTake').value.trim();if(!url)return;const arr=manualItems();arr.unshift({url,take,at:new Date().toISOString()});localStorage.setItem('creator-inbox',JSON.stringify(arr.slice(0,50)));$('manualUrl').value='';$('manualTake').value='';renderManual()};

async function loadLibrary(){let rows=[];if(STATE.storage?.configured){try{const r=await fetch('/api/drafts'),j=await r.json();rows=j.items||[]}catch{rows=localDrafts()}}else rows=localDrafts();STATE.drafts=rows;$('libraryMode').className=`badge ${STATE.storage?.configured?'good':'warn'}`;$('libraryMode').textContent=STATE.storage?.configured?'durable server library':'browser fallback';$('libraryList').innerHTML=rows.length?rows.map(x=>`<div class="draftCard"><div class="head"><div><h3>${esc(x.topic)}</h3><span class="badge ${String(x.status).includes('approved')?'good':'blue'}">${esc(x.platform)} · ${esc(x.status||'draft')}</span></div><span class="tiny">${esc((x.created_at||x.createdAt||'').slice(0,10))}</span></div><p>${esc(String(x.content||'').slice(0,260))}${String(x.content||'').length>260?'…':''}</p></div>`).join(''):'<div class="placeholder">No drafts yet.</div>'}

function browserProfile(){try{return JSON.parse(localStorage.getItem('creator-profile')||'null')}catch{return null}}
function fillProfile(p){p=p||{};$('memName').value=p.identity?.name||'';$('memRole').value=p.identity?.role||'';$('memBio').value=p.identity?.bio||'';$('memAudience').value=p.identity?.audience||'';$('memTone').value=p.voice?.tone||'';$('memExpertise').value=(p.expertise||[]).map(x=>typeof x==='string'?x:(x.topic||x.evidence||JSON.stringify(x))).join('\n')}
async function saveMemory(){const lines=$('memExpertise').value.split('\n').map(x=>x.trim()).filter(Boolean),profile={identity:{name:$('memName').value.trim(),role:$('memRole').value.trim(),bio:$('memBio').value.trim(),audience:$('memAudience').value.trim()},voice:{tone:$('memTone').value.trim()},expertise:lines.map((x,i)=>({id:`manual-${i+1}`,topic:x,evidence:x,tags:x.toLowerCase().split(/\s+/).slice(0,10)}))};try{if(STATE.storage?.configured){const r=await fetch('/api/memory',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(profile)}),j=await r.json();if(!r.ok)throw new Error(j.message||j.error);STATE.profile=j.profile}else{localStorage.setItem('creator-profile',JSON.stringify(profile));STATE.profile=profile}setNotice('memoryStatus',STATE.storage?.configured?'Creator memory saved durably.':'Creator memory saved in this browser; connect storage for durable cross-device memory.','good')}catch(e){setNotice('memoryStatus',`Memory save failed: ${e.message}`,'bad')}}
$('saveMemory').onclick=saveMemory;

function renderCapabilities(){const c=STATE.health?.capabilities||{},root=$('capGrid');root.innerHTML=Object.entries({Research:c.discover,'Primary-source enrichment':c.enrichPrimarySources,'Context + harness':c.harness,'Live writer':c.writer,'Signed approval':c.approval,'Durable memory':c.durableMemory,'LinkedIn direct publish':c.linkedinPublish,'Medium export':c.mediumExport,'Analytics loop':c.analytics}).map(([k,v])=>`<div class="cap"><b>${esc(k)}</b><span class="badge ${v?'good':'warn'}">${v?'ready':'pending'}</span></div>`).join('')}
function renderRuns(){$('lastRun').innerHTML=STATE.lastRun?`<div class="sourceItem"><b>${esc(STATE.lastRun.status)}</b><div>${esc(STATE.lastRun.runId)} · ${esc(STATE.lastRun.contract?.topic||'')}</div><div>${(STATE.lastRun.states||[]).map(x=>esc(x.state)).join(' → ')}</div></div>`:'<span class="tiny">No run in this browser yet.</span>'}

async function boot(){try{const [hR,tR,fR,hsR,psR,stR]=await Promise.all([fetch('/api/health'),fetch('/api/today'),fetch('/api/research-focus'),fetch('/api/harness-selftest'),fetch('/api/product-selftest'),fetch('/api/storage-health')]);const h=await hR.json(),t=await tR.json(),f=await fR.json(),hs=await hsR.json(),ps=await psR.json(),st=await stR.json();STATE.health=h;STATE.storage=st;STATE.feed=t.items||[];STATE.sources=t.sources||[];$('sideHealth').textContent=h.ok?'Creator agent online':'Creator agent degraded';$('sideDetail').textContent=`research ${h.capabilities?.discover?'on':'off'} · writer ${h.capabilities?.writer?'on':'off'} · storage ${h.capabilities?.durableMemory?'on':'off'}`;$('feedPolicy').textContent=t.sourcePolicy||'official sources';$('topicChips').innerHTML=(f.topics||[]).map(x=>`<span class="chip">${esc(x.label)}</span>`).join('');$('harnessTest').innerHTML=`<b>${hs.ok?'Harness certification passed':'Harness certification failed'}</b><div class="tiny" style="margin-top:7px">${Object.entries(hs.checks||{}).map(([k,v])=>`${esc(k)}=${v?'pass':'fail'}`).join(' · ')}</div>`;$('productTest').innerHTML=`<b>${ps.ok?'Product contract passed':'Product contract failed'}</b><div class="tiny" style="margin-top:7px">${Object.entries(ps.checks||{}).map(([k,v])=>`${esc(k)}=${v?'pass':'fail'}`).join(' · ')}</div>`;if(st.configured){try{const m=await fetch('/api/memory'),mj=await m.json();STATE.profile=mj.profile||null}catch{}}if(!STATE.profile)STATE.profile=browserProfile();fillProfile(STATE.profile);STATE.drafts=st.configured?[]:localDrafts();renderToday();renderResearch();renderManual();renderCapabilities();$('storageBadge').className=`badge ${st.configured?'good':'warn'}`;$('storageBadge').textContent=st.configured?'durable storage connected':'durable storage pending';$('writerBadge').className=`badge ${h.capabilities?.writer?'good':'warn'}`;$('writerBadge').textContent=h.capabilities?.writer?'writer connected':'writer credential pending';$('publisherBadge').className=`badge ${h.capabilities?.linkedinPublish?'good':'warn'}`;$('publisherBadge').textContent=h.capabilities?.linkedinPublish?'LinkedIn connected':'LinkedIn credentials pending';if(!h.capabilities?.writer)setNotice('composeStatus','Research, evidence, context, critic and approval infrastructure are online. Generation remains blocked until the OpenAI API credential is connected.','warn');}catch(e){$('todayFeed').innerHTML=`<div class="placeholder">Creator Console failed to initialize: ${esc(e.message)}</div>`;$('sideHealth').textContent='Initialization failed'}}
boot();
