'use strict';
const {sign,verify}=require('../lib/approval');
const store=require('../lib/store');
const {discover}=require('../lib/research-agent');
const {buildBriefBundle}=require('../lib/content-brief');
const {runBriefSelftest}=require('../lib/brief-selftest');

function bodyOf(req){return typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{})}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function toHtml(text){return String(text||'').split(/\n{2,}/).map(block=>{const t=block.trim();if(!t)return'';if(/^#{1,3}\s+/.test(t)){const level=Math.min(3,(t.match(/^#+/)||['#'])[0].length);return`<h${level}>${esc(t.replace(/^#{1,3}\s+/,''))}</h${level}>`}return`<p>${esc(t).replace(/\n/g,'<br>')}</p>`}).join('\n')}
function requireMethod(req,res,method){if(req.method===method)return true;res.status(405).json({error:'METHOD_NOT_ALLOWED',allowed:[method]});return false}
function allowedReferenceUrl(raw){let u;try{u=new URL(String(raw||''))}catch{return null}if(u.protocol!=='https:')return null;const host=u.hostname.toLowerCase();return['lnkd.in','linkedin.com','www.linkedin.com','reddit.com','www.reddit.com','old.reddit.com','new.reddit.com'].includes(host)?u:null}
function htmlMeta(html){const text=String(html||'');const title=(text.match(/<meta[^>]+property=["']og:title["'][^>]+content=["']([^"']+)["']/i)?.[1]||text.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]||'').replace(/\s+/g,' ').trim();const description=(text.match(/<meta[^>]+(?:property|name)=["'](?:og:description|description)["'][^>]+content=["']([^"']+)["']/i)?.[1]||'').replace(/\s+/g,' ').trim();return{title:title.slice(0,500),description:description.slice(0,1200)}}
async function resolveReference(raw){let current=allowedReferenceUrl(raw);if(!current){const e=new Error('Only HTTPS LinkedIn and Reddit URLs are accepted.');e.code='REFERENCE_URL_NOT_ALLOWED';e.status=400;throw e}const visited=[];for(let i=0;i<6;i++){visited.push(current.toString());const r=await fetch(current,{redirect:'manual',headers:{'User-Agent':'Mozilla/5.0 (compatible; CreatorConsoleReferenceResolver/1.0)','Accept':'text/html,application/xhtml+xml,application/json;q=0.8,*/*;q=0.5'}});if(r.status>=300&&r.status<400){const loc=r.headers.get('location');if(!loc)break;const next=allowedReferenceUrl(new URL(loc,current).toString());if(!next){const e=new Error('Redirect left the approved LinkedIn/Reddit host set.');e.code='REFERENCE_REDIRECT_NOT_ALLOWED';e.status=400;throw e}current=next;continue}const contentType=r.headers.get('content-type')||'',text=await r.text(),meta=/html/i.test(contentType)?htmlMeta(text):{title:'',description:''};return{schema:'creator-reference-resolution/v1',inputUrl:String(raw),finalUrl:current.toString(),resolved:current.toString()!==String(raw),httpStatus:r.status,contentType,title:meta.title,description:meta.description,visited}}return{schema:'creator-reference-resolution/v1',inputUrl:String(raw),finalUrl:current.toString(),resolved:current.toString()!==String(raw),httpStatus:null,contentType:null,title:'',description:'',visited,warning:'Redirect limit reached before a terminal response.'}}

async function handleApprove(req,res){if(!requireMethod(req,res,'POST'))return;const body=bodyOf(req),receipt=body.runReceipt||{};if(receipt.schema!=='creator-run-receipt/v1'||receipt.status!=='approval-required')return res.status(409).json({error:'RUN_NOT_APPROVABLE',message:'Only quality-passed runs waiting for approval can be approved.'});const drafts=body.drafts&&typeof body.drafts==='object'?body.drafts:{},approvals={};for(const p of receipt.platforms||[]){const draft=String(drafts[p]||'').trim();if(!draft)return res.status(400).json({error:'DRAFT_REQUIRED',message:`Missing ${p} draft.`});approvals[p]=sign({runId:receipt.runId,platform:p,draft})}return res.status(200).json({ok:true,schema:'creator-approval-bundle/v1',runId:receipt.runId,approvals})}
async function handleLinkedIn(req,res){if(!requireMethod(req,res,'POST'))return;const body=bodyOf(req),draft=String(body.draft||'').trim(),approval=body.approval;if(!draft)return res.status(400).json({error:'DRAFT_REQUIRED'});const gate=verify(approval,{draft,platform:'linkedin'});if(!gate.passed)return res.status(409).json({error:'APPROVAL_REQUIRED',issues:gate.errors});const token=process.env.LINKEDIN_ACCESS_TOKEN,author=process.env.LINKEDIN_AUTHOR_URN,version=process.env.LINKEDIN_VERSION||'202609';if(!token||!author)return res.status(503).json({error:'LINKEDIN_NOT_CONNECTED',message:'LinkedIn publishing credentials are not configured.'});const payload={author,commentary:draft,visibility:'PUBLIC',distribution:{feedDistribution:'MAIN_FEED',targetEntities:[],thirdPartyDistributionChannels:[]},lifecycleState:'PUBLISHED',isReshareDisabledByAuthor:false};const r=await fetch('https://api.linkedin.com/rest/posts',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json','Linkedin-Version':version,'X-Restli-Protocol-Version':'2.0.0'},body:JSON.stringify(payload)}),text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{data={raw:text.slice(0,1000)}}if(!r.ok)return res.status(r.status).json({error:'LINKEDIN_PUBLISH_FAILED',status:r.status,details:data});const postId=r.headers.get('x-restli-id')||data?.id||null,receipt={ok:true,schema:'creator-publication-receipt/v1',platform:'linkedin',runId:approval.runId,postId,publishedAt:new Date().toISOString(),draftHash:approval.draftHash,linkedinVersion:version};if(store.capability('publications')){try{await store.savePublication({runId:approval.runId,platform:'linkedin',postId,draftHash:approval.draftHash,publishedAt:receipt.publishedAt,receipt})}catch{}}return res.status(201).json(receipt)}
async function handleMedium(req,res){if(!requireMethod(req,res,'POST'))return;const body=bodyOf(req),draft=String(body.draft||'').trim();if(!draft)return res.status(400).json({error:'DRAFT_REQUIRED'});const title=String(body.title||'Creator Console article').trim().slice(0,220),subtitle=String(body.subtitle||'').trim().slice(0,300),html=`<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title></head><body><article><h1>${esc(title)}</h1>${subtitle?`<p><em>${esc(subtitle)}</em></p>`:''}${toHtml(draft)}</article></body></html>`;return res.status(200).json({ok:true,schema:'creator-medium-export/v1',title,subtitle,html,markdown:draft,workflow:'manual-import-or-paste'})}
async function handleDrafts(req,res){const c=store.config();if(req.method==='GET')return res.status(200).json({ok:true,configured:c.configured,provider:c.provider,items:store.capability('drafts')?await store.listDrafts(Number(req.query?.limit||50)):[]});if(req.method==='POST'){if(!store.capability('drafts'))throw Object.assign(new Error('Draft persistence is not configured'),{code:'STORAGE_NOT_CONFIGURED'});return res.status(201).json({ok:true,item:await store.saveDraft(bodyOf(req))})}return res.status(405).json({error:'METHOD_NOT_ALLOWED'})}
async function handleMemory(req,res){const c=store.config();if(req.method==='GET')return res.status(200).json({ok:true,configured:c.configured,provider:c.provider,profile:store.capability('profile')?await store.getProfile():null});if(req.method==='POST'){if(!store.capability('profile'))throw Object.assign(new Error('Profile persistence is not configured'),{code:'STORAGE_NOT_CONFIGURED'});return res.status(200).json({ok:true,profile:await store.saveProfile(bodyOf(req))})}return res.status(405).json({error:'METHOD_NOT_ALLOWED'})}
async function handleBriefEvaluate(req,res){if(!requireMethod(req,res,'POST'))return;const bundle=buildBriefBundle(bodyOf(req)),h=await store.health();return res.status(200).json({ok:true,persistence:h.connected?'available':(h.configured?'configured-unreachable':'not-configured'),persistenceProvider:h.provider,...bundle})}
async function handleBriefSelftest(req,res){if(!requireMethod(req,res,'GET'))return;const h=await store.health();return res.status(200).json({...runBriefSelftest(),persistenceConfigured:h.configured,persistenceConnected:h.connected,persistenceProvider:h.provider})}
async function handleBriefs(req,res){const c=store.config();if(req.method==='GET'){if(!store.capability('briefs'))return res.status(200).json({ok:true,configured:false,provider:c.provider,items:[]});const id=String(req.query?.id||'').trim();if(id){const bundle=await store.getBriefBundle(id);if(!bundle)return res.status(404).json({error:'BRIEF_NOT_FOUND'});return res.status(200).json({ok:true,configured:true,provider:c.provider,brief:bundle.brief,sources:bundle.sources,claims:bundle.claims})}return res.status(200).json({ok:true,configured:true,provider:c.provider,items:await store.listBriefs(Number(req.query?.limit||50))})}if(req.method==='POST'){if(!store.capability('briefs'))throw Object.assign(new Error('Content Brief persistence is not configured'),{code:'STORAGE_NOT_CONFIGURED'});const body=bodyOf(req),brief=body.brief||body,sources=Array.isArray(body.sources)?body.sources:[],claims=Array.isArray(body.claims)?body.claims:[],saved=await store.saveBriefBundle({brief,sources,claims});return res.status(201).json({ok:true,schema:'creator-content-brief-bundle/v1',provider:c.provider,...saved})}return res.status(405).json({error:'METHOD_NOT_ALLOWED'})}
async function handleStorage(req,res){if(!requireMethod(req,res,'GET'))return;const h=await store.health();return res.status(200).json({ok:true,configured:h.configured,connected:h.connected,provider:h.provider,mode:h.connected?'durable-server-storage':(h.configured?'configured-unreachable':'browser-fallback'),capabilities:h.capabilities||{},error:h.error||null,dataObjects:['creator_profiles','creator_research_items','creator_content_briefs','creator_sources','creator_claims','creator_drafts','creator_publications']})}
async function handlePublications(req,res){if(!requireMethod(req,res,'GET'))return;const c=store.config();return res.status(200).json({ok:true,configured:c.configured,provider:c.provider,items:store.capability('publications')?await store.listPublications(Number(req.query?.limit||50)):[]})}
async function handleDiscover(req,res){if(!requireMethod(req,res,'GET'))return;const result=await discover({limit:Math.max(1,Math.min(50,Number(req.query?.limit||20)))});return res.status(200).json({ok:true,...result})}
async function handleResolveReference(req,res){if(!requireMethod(req,res,'GET'))return;return res.status(200).json({ok:true,...await resolveReference(req.query?.url)})}

module.exports=async function(req,res){res.setHeader('Cache-Control','no-store');const op=String(req.query?.op||'');try{if(op==='approve')return handleApprove(req,res);if(op==='publish-linkedin')return handleLinkedIn(req,res);if(op==='export-medium')return handleMedium(req,res);if(op==='drafts')return handleDrafts(req,res);if(op==='memory')return handleMemory(req,res);if(op==='brief-evaluate')return handleBriefEvaluate(req,res);if(op==='brief-selftest')return handleBriefSelftest(req,res);if(op==='briefs')return handleBriefs(req,res);if(op==='storage-health')return handleStorage(req,res);if(op==='publications')return handlePublications(req,res);if(op==='discover')return handleDiscover(req,res);if(op==='resolve-reference')return handleResolveReference(req,res);return res.status(404).json({error:'UNKNOWN_ACTION'})}catch(e){const status=e.code==='STORAGE_NOT_CONFIGURED'?503:(e.status||400);return res.status(status).json({error:e.code||'ACTION_FAILED',message:String(e.message||e),details:e.details||null})}}
