'use strict';
const {sign,verify}=require('../lib/approval');
const store=require('../lib/store');
const {discover}=require('../lib/research-agent');
function bodyOf(req){return typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{})}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function toHtml(text){return String(text||'').split(/\n{2,}/).map(block=>{const t=block.trim();if(!t)return'';if(/^#{1,3}\s+/.test(t)){const level=Math.min(3,(t.match(/^#+/)||['#'])[0].length);return`<h${level}>${esc(t.replace(/^#{1,3}\s+/,''))}</h${level}>`}return`<p>${esc(t).replace(/\n/g,'<br>')}</p>`}).join('\n')}
function requireMethod(req,res,method){if(req.method===method)return true;res.status(405).json({error:'METHOD_NOT_ALLOWED',allowed:[method]});return false}
async function handleApprove(req,res){if(!requireMethod(req,res,'POST'))return;const body=bodyOf(req),receipt=body.runReceipt||{};if(receipt.schema!=='creator-run-receipt/v1'||receipt.status!=='approval-required')return res.status(409).json({error:'RUN_NOT_APPROVABLE',message:'Only quality-passed runs waiting for approval can be approved.'});const drafts=body.drafts&&typeof body.drafts==='object'?body.drafts:{},approvals={};for(const p of receipt.platforms||[]){const draft=String(drafts[p]||'').trim();if(!draft)return res.status(400).json({error:'DRAFT_REQUIRED',message:`Missing ${p} draft.`});approvals[p]=sign({runId:receipt.runId,platform:p,draft});}return res.status(200).json({ok:true,schema:'creator-approval-bundle/v1',runId:receipt.runId,approvals})}
async function handleLinkedIn(req,res){if(!requireMethod(req,res,'POST'))return;const body=bodyOf(req),draft=String(body.draft||'').trim(),approval=body.approval;if(!draft)return res.status(400).json({error:'DRAFT_REQUIRED'});const gate=verify(approval,{draft,platform:'linkedin'});if(!gate.passed)return res.status(409).json({error:'APPROVAL_REQUIRED',issues:gate.errors});const token=process.env.LINKEDIN_ACCESS_TOKEN,author=process.env.LINKEDIN_AUTHOR_URN,version=process.env.LINKEDIN_VERSION||'202609';if(!token||!author)return res.status(503).json({error:'LINKEDIN_NOT_CONNECTED',message:'Set LINKEDIN_ACCESS_TOKEN and LINKEDIN_AUTHOR_URN after authorizing w_member_social.'});const payload={author,commentary:draft,visibility:'PUBLIC',distribution:{feedDistribution:'MAIN_FEED',targetEntities:[],thirdPartyDistributionChannels:[]},lifecycleState:'PUBLISHED',isReshareDisabledByAuthor:false};const r=await fetch('https://api.linkedin.com/rest/posts',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json','Linkedin-Version':version,'X-Restli-Protocol-Version':'2.0.0'},body:JSON.stringify(payload)});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{data={raw:text.slice(0,1000)}}if(!r.ok)return res.status(r.status).json({error:'LINKEDIN_PUBLISH_FAILED',status:r.status,details:data});const postId=r.headers.get('x-restli-id')||data?.id||null;const receipt={ok:true,schema:'creator-publication-receipt/v1',platform:'linkedin',runId:approval.runId,postId,publishedAt:new Date().toISOString(),draftHash:approval.draftHash,linkedinVersion:version};if(store.config().configured){try{await store.savePublication({runId:approval.runId,platform:'linkedin',postId,draftHash:approval.draftHash,receipt})}catch{}}return res.status(201).json(receipt)}
async function handleMedium(req,res){if(!requireMethod(req,res,'POST'))return;const body=bodyOf(req),draft=String(body.draft||'').trim();if(!draft)return res.status(400).json({error:'DRAFT_REQUIRED'});const title=String(body.title||'Creator Console article').trim().slice(0,220),subtitle=String(body.subtitle||'').trim().slice(0,300),html=`<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title></head><body><article><h1>${esc(title)}</h1>${subtitle?`<p><em>${esc(subtitle)}</em></p>`:''}${toHtml(draft)}</article></body></html>`;return res.status(200).json({ok:true,schema:'creator-medium-export/v1',title,subtitle,html,markdown:draft,workflow:'manual-import-or-paste',note:'Medium does not issue new API integration tokens; existing-token integrations can be added separately when available.'})}
async function handleDrafts(req,res){if(req.method==='GET')return res.status(200).json({ok:true,configured:store.config().configured,items:store.config().configured?await store.listDrafts(Number(req.query?.limit||50)):[]});if(req.method==='POST')return res.status(201).json({ok:true,items:await store.saveDraft(bodyOf(req))});return res.status(405).json({error:'METHOD_NOT_ALLOWED'})}
async function handleMemory(req,res){if(req.method==='GET')return res.status(200).json({ok:true,configured:store.config().configured,profile:store.config().configured?await store.getProfile():null});if(req.method==='POST'){const saved=await store.saveProfile(bodyOf(req));return res.status(200).json({ok:true,profile:Array.isArray(saved)?saved[0]:saved})}return res.status(405).json({error:'METHOD_NOT_ALLOWED'})}
async function handleStorage(req,res){if(!requireMethod(req,res,'GET'))return;const c=store.config();return res.status(200).json({ok:true,configured:c.configured,provider:'supabase-postgrest',mode:c.configured?'durable-server-storage':'browser-fallback',tables:['creator_profiles','creator_research_items','creator_drafts','creator_publications']})}
async function handlePublications(req,res){if(!requireMethod(req,res,'GET'))return;return res.status(200).json({ok:true,configured:store.config().configured,items:store.config().configured?await store.listPublications(Number(req.query?.limit||50)):[]})}
async function handleDiscover(req,res){if(!requireMethod(req,res,'GET'))return;const result=await discover({limit:Math.max(1,Math.min(50,Number(req.query?.limit||20)))});return res.status(200).json({ok:true,...result})}
module.exports=async function(req,res){res.setHeader('Cache-Control','no-store');const op=String(req.query?.op||'');try{if(op==='approve')return handleApprove(req,res);if(op==='publish-linkedin')return handleLinkedIn(req,res);if(op==='export-medium')return handleMedium(req,res);if(op==='drafts')return handleDrafts(req,res);if(op==='memory')return handleMemory(req,res);if(op==='storage-health')return handleStorage(req,res);if(op==='publications')return handlePublications(req,res);if(op==='discover')return handleDiscover(req,res);return res.status(404).json({error:'UNKNOWN_ACTION'});}catch(e){const status=e.code==='STORAGE_NOT_CONFIGURED'?503:(e.status||400);return res.status(status).json({error:e.code||'ACTION_FAILED',message:String(e.message||e),details:e.details||null});}}
