'use strict';
const defaultReferences = [...require('../data/references.json'),...require('../data/reference-inbox.json')];
const STOP = new Set(['the','a','an','and','or','but','to','of','in','on','for','with','is','are','was','were','be','been','being','that','this','these','those','it','its','as','at','by','from','about','into','over','after','before','we','you','i','they','he','she','them','our','your','my','their','not','can','could','should','would','will','do','does']);
function tokenize(v){return String(v||'').toLowerCase().replace(/https?:\/\/\S+/g,' ').replace(/[^a-z0-9+#.\- ]+/g,' ').split(/\s+/).map(x=>x.trim()).filter(x=>x.length>1&&!STOP.has(x));}
function unique(v){return [...new Set(v.filter(Boolean))];}
function scoreText(q,text,tags=[]){const d=tokenize(`${text||''} ${(tags||[]).join(' ')}`),set=new Set(d);let s=0;for(const t of q){if(set.has(t))s+=1;if(String(text||'').toLowerCase().includes(t))s+=.15;if(new Set(tokenize((tags||[]).join(' '))).has(t))s+=.7;}return s;}
function recencyBoost(v){const t=Date.parse(v||'');if(!Number.isFinite(t))return 0;const d=Math.max(0,(Date.now()-t)/86400000);return d<=30?.6:d<=180?.35:d<=365?.15:0;}
function normalizeContext(input={}){return{identity:{name:String(input.identity?.name||'').slice(0,120),role:String(input.identity?.role||'').slice(0,240),bio:String(input.identity?.bio||'').slice(0,3000),audience:String(input.identity?.audience||'').slice(0,1200),goals:String(input.identity?.goals||'').slice(0,1200)},voice:{tone:String(input.voice?.tone||'').slice(0,1000),dos:Array.isArray(input.voice?.dos)?input.voice.dos.slice(0,30).map(String):[],donts:Array.isArray(input.voice?.donts)?input.voice.donts.slice(0,30).map(String):[],examples:Array.isArray(input.voice?.examples)?input.voice.examples.slice(0,8).map(String):[]},expertise:Array.isArray(input.expertise)?input.expertise.slice(0,100):[],knowledge:Array.isArray(input.knowledge)?input.knowledge.slice(0,250):[],history:Array.isArray(input.history)?input.history.slice(0,250):[],references:Array.isArray(input.references)?input.references.slice(0,250):defaultReferences};}
function buildContextPacket({topic,platform='linkedin',objective='',context={},topK=10}){const clean=normalizeContext(context),q=unique(tokenize(`${topic} ${objective} ${platform}`)),c=[];
for(const x of clean.expertise){const text=[x.topic,x.level,x.evidence,x.notes].filter(Boolean).join(' — ');c.push({type:'expertise',id:String(x.id||x.topic||`e-${c.length}`),title:String(x.topic||'Expertise'),text:String(text).slice(0,4000),tags:Array.isArray(x.tags)?x.tags.map(String).slice(0,20):[],score:scoreText(q,text,x.tags)+1.25,trust:'author-owned'});}
for(const x of clean.knowledge){const text=[x.title,x.content].filter(Boolean).join('\n');c.push({type:'knowledge',id:String(x.id||x.title||`k-${c.length}`),title:String(x.title||'Knowledge source'),text:String(x.content||'').slice(0,7000),sourceUrl:x.sourceUrl?String(x.sourceUrl).slice(0,1600):null,tags:Array.isArray(x.tags)?x.tags.map(String).slice(0,20):[],score:scoreText(q,text,x.tags)+recencyBoost(x.createdAt),trust:'evidence'});}
for(const x of clean.history){const text=[x.topic,x.summary,x.content].filter(Boolean).join('\n'),same=String(x.platform||'').toLowerCase()===String(platform).toLowerCase()?.65:0;c.push({type:'prior-content',id:String(x.id||`h-${c.length}`),title:String(x.topic||'Prior content'),text:String(x.summary||x.content||'').slice(0,5000),platform:String(x.platform||''),tags:Array.isArray(x.tags)?x.tags.map(String).slice(0,20):[],score:scoreText(q,text,x.tags)+same+recencyBoost(x.createdAt),trust:'author-owned'});}
for(const x of clean.references){const text=[x.creator,x.topic,x.notes,(x.signals||[]).join(' ')].filter(Boolean).join('\n');c.push({type:'reference-pattern',id:String(x.id||`r-${c.length}`),title:`${x.creator||'Reference'} — ${x.topic||'post'}`,text:String(x.notes||x.topic||'').slice(0,4000),sourceUrl:String(x.url||''),tags:Array.isArray(x.signals)?x.signals.map(String).slice(0,20):[],score:scoreText(q,text,x.signals)+.45,trust:'style-only'});}
const selected=c.filter(x=>x.score>.15).sort((a,b)=>b.score-a.score||a.title.localeCompare(b.title)).slice(0,Math.max(1,Math.min(24,topK))).map(x=>({...x,score:Number(x.score.toFixed(3))}));
return{schema:'creator-context-packet/v2',topic:String(topic||'').slice(0,1000),platform:String(platform).toLowerCase(),objective:String(objective).slice(0,1600),identity:clean.identity,voice:clean.voice,selected,retrieval:{strategy:'deterministic-ranked-context-v2',queryTokens:q,candidateCount:c.length,selectedCount:selected.length,excludedCount:Math.max(0,c.length-selected.length)},guardrails:{neverInventPersonalExperience:true,distinguishEvidenceFromOpinion:true,referencePatternsAreStyleOnly:true,neverCopyReferenceWording:true,doNotPresentUnverifiedClaimsAsFacts:true,avoidNearDuplicatePriorContent:true}};}
module.exports={tokenize,scoreText,normalizeContext,buildContextPacket};
