'use strict';
const crypto=require('crypto');
const seed=require('../data/today.json');

const SOURCES=[
  {id:'openai',vendor:'OpenAI',url:'https://openai.com/news/',kind:'official-news',patterns:['/index/','/news/']},
  {id:'anthropic',vendor:'Anthropic',url:'https://www.anthropic.com/news',kind:'official-news',patterns:['/news/']},
  {id:'snowflake',vendor:'Snowflake',url:'https://www.snowflake.com/en/blog/',kind:'official-blog',patterns:['/en/blog/']},
  {id:'databricks',vendor:'Databricks',url:'https://www.databricks.com/blog',kind:'official-blog',patterns:['/blog/']}
];
const TOPIC_TERMS=['snowflake','databricks','openai','anthropic','claude','codex','llm','rag','agent','agents','model','ai','iceberg','cortex','unity catalog'];
function hash(v){return crypto.createHash('sha256').update(String(v)).digest('hex').slice(0,16)}
function stripHtml(s){return String(s||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g,' ').trim()}
function absolutize(base,href){try{return new URL(href,base).toString()}catch{return null}}
function sameHost(a,b){try{return new URL(a).hostname===new URL(b).hostname}catch{return false}}
function relevant(title,url){const s=`${title} ${url}`.toLowerCase();return TOPIC_TERMS.some(t=>s.includes(t))}
function dateFromText(text){const tests=[/\b(20\d{2})-(\d{2})-(\d{2})\b/,/\b(January|February|March|April|May|June|July|August|September|October|November|December)\s+(\d{1,2}),\s+(20\d{2})\b/i];for(const rx of tests){const m=String(text||'').match(rx);if(!m)continue;const d=Date.parse(m[0]);if(Number.isFinite(d))return new Date(d).toISOString().slice(0,10)}return null}
function extractLinks(html,source){const out=[],seen=new Set();const rx=/<a\b[^>]*href=["']([^"'#]+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=rx.exec(String(html||'')))&&out.length<80){const url=absolutize(source.url,m[1]),title=stripHtml(m[2]);if(!url||!sameHost(url,source.url)||title.length<18||title.length>180)continue;if(!source.patterns.some(p=>url.includes(p)))continue;if(seen.has(url))continue;seen.add(url);if(!relevant(title,url))continue;out.push({url,title,publishedAt:dateFromText(`${title} ${url}`)});}return out}
function score(item){let fit=3,novelty=3,evidence=5,teachability=3;const s=`${item.title} ${item.url}`.toLowerCase();if(TOPIC_TERMS.some(t=>s.includes(t)))fit=5;if(/introduc|announc|release|launch|new|preview|ga\b|general availability|model|agent|rag|iceberg|cortex|unity/i.test(s))novelty=5;if(/architecture|cost|latency|govern|security|benchmark|evaluation|migration|inference|data/i.test(s))teachability=5;const potential=Math.round((fit+novelty+evidence+teachability)/20*100);return{fit,novelty,evidence,teachability,potential}}
function angleSuggestions(item){const v=item.vendor,t=item.title;return[`What changed in ${v} and why should a data/AI architect care?`,`How does ${t} change the architecture or operating model?`,`What are the practical trade-offs behind this announcement?`]}
async function fetchPage(source,{timeoutMs=8000}={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);try{const r=await fetch(source.url,{headers:{'User-Agent':'CreatorConsoleResearchAgent/1.0 (+https://creator-console-rrahul0904-5013s-projects.vercel.app)','Accept':'text/html,application/xhtml+xml'},redirect:'follow',signal:controller.signal});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.text()}finally{clearTimeout(timer)}}
function normalize(source,link){const sig=score({...link,vendor:source.vendor});return{id:`live-${source.id}-${hash(link.url)}`,vendor:source.vendor,topic:link.title,publishedAt:link.publishedAt,sourceTitle:link.title,sourceUrl:link.url,summary:`New item discovered from ${source.vendor}'s official source surface. Open the primary source before drafting and verify the exact product claims.`,whyItMatters:'This item matched the Creator Console research universe and is being surfaced for evidence review before it can become a post.',categories:[source.vendor,'AI / Data'],signals:{fit:sig.fit,novelty:sig.novelty,evidence:sig.evidence,teachability:sig.teachability},angleSuggestions:angleSuggestions({...link,vendor:source.vendor}),educationalPotential:sig.potential,status:'discovered-needs-evidence-review',discovery:{mode:'official-source-crawl',sourceId:source.id,sourceKind:source.kind,discoveredAt:new Date().toISOString()}}}
function seedItems(){return seed.map(x=>({...x,status:'verified-seed',educationalPotential:Math.round(['fit','novelty','evidence','teachability'].map(k=>Number(x.signals?.[k]||0)).reduce((a,b)=>a+b,0)/20*100),discovery:{mode:'verified-seed'}}))}
function dedupe(items){const seen=new Set(),out=[];for(const x of items){const key=(x.sourceUrl||x.topic||'').toLowerCase().replace(/\?.*$/,'').replace(/\/$/,'');if(!key||seen.has(key))continue;seen.add(key);out.push(x)}return out}
async function discover({limit=20}={}){const results=await Promise.allSettled(SOURCES.map(async source=>{const html=await fetchPage(source);return{source,links:extractLinks(html,source)}}));const live=[],sources=[];for(let i=0;i<results.length;i++){const r=results[i],source=SOURCES[i];if(r.status==='fulfilled'){sources.push({id:source.id,vendor:source.vendor,ok:true,count:r.value.links.length});live.push(...r.value.links.map(x=>normalize(source,x)))}else sources.push({id:source.id,vendor:source.vendor,ok:false,count:0,error:String(r.reason?.message||r.reason).slice(0,180)});}const merged=dedupe([...live,...seedItems()]).sort((a,b)=>(b.educationalPotential||0)-(a.educationalPotential||0)||Date.parse(b.publishedAt||0)-Date.parse(a.publishedAt||0)).slice(0,Math.max(1,Math.min(50,limit)));return{schema:'creator-research-discovery/v1',generatedAt:new Date().toISOString(),sourcePolicy:'official-source-crawl-with-verified-seed-fallback',sources,liveDiscoveryCount:live.length,items:merged};}
module.exports={SOURCES,TOPIC_TERMS,stripHtml,extractLinks,score,dedupe,discover};
