'use strict';
const crypto=require('crypto');
const seed=require('../data/today.json');

const SOURCES=[
  {id:'openai',vendor:'OpenAI',url:'https://openai.com/news/',feedUrl:'https://openai.com/news/rss.xml',kind:'official-news',patterns:['/index/','/news/']},
  {id:'anthropic',vendor:'Anthropic',url:'https://www.anthropic.com/news',kind:'official-news',patterns:['/news/']},
  {id:'snowflake',vendor:'Snowflake',url:'https://www.snowflake.com/en/blog/',kind:'official-blog',patterns:['/en/blog/']},
  {id:'databricks',vendor:'Databricks',url:'https://www.databricks.com/blog',kind:'official-blog',patterns:['/blog/']}
];
const TOPIC_TERMS=['snowflake','databricks','openai','anthropic','claude','codex','llm','rag','agent','agents','model','ai','iceberg','cortex','unity catalog'];
function hash(v){return crypto.createHash('sha256').update(String(v)).digest('hex').slice(0,16)}
function decodeEntities(s){return String(s||'').replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>')}
function stripHtml(s){return decodeEntities(String(s||'')).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()}
function absolutize(base,href){try{return new URL(href,base).toString()}catch{return null}}
function sameHost(a,b){try{return new URL(a).hostname===new URL(b).hostname}catch{return false}}
function relevant(title,url){const s=`${title} ${url}`.toLowerCase();return TOPIC_TERMS.some(t=>s.includes(t))}
function dateFromText(text){const tests=[/\b(20\d{2})-(\d{2})-(\d{2})\b/,/\b(January|February|March|April|May|June|July|August|September|October|November|December|Jan|Feb|Mar|Apr|Jun|Jul|Aug|Sep|Sept|Oct|Nov|Dec)\s+(\d{1,2}),\s+(20\d{2})\b/i];for(const rx of tests){const m=String(text||'').match(rx);if(!m)continue;const d=Date.parse(m[0]);if(Number.isFinite(d))return new Date(d).toISOString().slice(0,10)}return null}
function extractLinks(html,source){const out=[],seen=new Set();const rx=/<a\b[^>]*href=["']([^"'#]+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=rx.exec(String(html||'')))&&out.length<100){const url=absolutize(source.url,m[1]),title=stripHtml(m[2]);if(!url||!sameHost(url,source.url)||title.length<18||title.length>220)continue;if(!source.patterns.some(p=>url.includes(p)))continue;if(seen.has(url))continue;seen.add(url);if(!relevant(title,url))continue;out.push({url,title,publishedAt:dateFromText(`${title} ${url}`)});}return out}
function extractTag(block,name){const rx=new RegExp(`<${name}[^>]*>([\\s\\S]*?)<\\/${name}>`,'i'),m=String(block||'').match(rx);return m?stripHtml(m[1]):''}
function parseFeed(xml,source){const out=[];const blocks=String(xml||'').match(/<item\b[\s\S]*?<\/item>|<entry\b[\s\S]*?<\/entry>/gi)||[];for(const b of blocks){const title=extractTag(b,'title');let url=extractTag(b,'link');if(!url){const m=b.match(/<link\b[^>]*href=["']([^"']+)["']/i);url=m?.[1]||''}url=absolutize(source.url,url);if(!title||!url||!sameHost(url,source.url)||!relevant(title,url))continue;const rawDate=extractTag(b,'pubDate')||extractTag(b,'published')||extractTag(b,'updated');const d=Date.parse(rawDate);out.push({url,title,publishedAt:Number.isFinite(d)?new Date(d).toISOString().slice(0,10):dateFromText(`${title} ${url}`)});if(out.length>=80)break}return dedupe(out.map(x=>({sourceUrl:x.url,...x}))).map(({sourceUrl,...x})=>x)}
function score(item){let fit=3,novelty=3,evidence=5,teachability=3;const s=`${item.title} ${item.url}`.toLowerCase();if(TOPIC_TERMS.some(t=>s.includes(t)))fit=5;if(/introduc|announc|release|launch|new|preview|ga\b|general availability|model|agent|rag|iceberg|cortex|unity/i.test(s))novelty=5;if(/architecture|cost|latency|govern|security|benchmark|evaluation|migration|inference|data|observability|postgres|mcp/i.test(s))teachability=5;const potential=Math.round((fit+novelty+evidence+teachability)/20*100);return{fit,novelty,evidence,teachability,potential}}
function angleSuggestions(item){const v=item.vendor,t=item.title;return[`What changed in ${v} and why should a data/AI architect care?`,`How does ${t} change the architecture or operating model?`,`What are the practical trade-offs behind this announcement?`]}
async function fetchText(url,{timeoutMs=8000,accept='text/html,application/xhtml+xml,application/xml,text/xml'}={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);try{const r=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0 CreatorConsoleResearchAgent/1.1','Accept':accept},redirect:'follow',signal:controller.signal});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.text()}finally{clearTimeout(timer)}}
async function fetchSource(source){if(source.feedUrl){try{const xml=await fetchText(source.feedUrl,{accept:'application/rss+xml,application/atom+xml,application/xml,text/xml,*/*'});const links=parseFeed(xml,source);if(links.length)return{mode:'rss',links}}catch{}}
  const html=await fetchText(source.url);return{mode:'html',links:extractLinks(html,source)};
}
function meta(html,key){const escaped=key.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const tests=[new RegExp(`<meta[^>]+(?:property|name)=["']${escaped}["'][^>]+content=["']([^"']+)["'][^>]*>`,'i'),new RegExp(`<meta[^>]+content=["']([^"']+)["'][^>]+(?:property|name)=["']${escaped}["'][^>]*>`,'i')];for(const rx of tests){const m=String(html||'').match(rx);if(m)return stripHtml(m[1])}return''}
function detailMetadata(html){const description=meta(html,'og:description')||meta(html,'description')||meta(html,'twitter:description');const rawDate=meta(html,'article:published_time')||meta(html,'date')||meta(html,'datePublished')||String(html||'').match(/"datePublished"\s*:\s*"([^"]+)"/i)?.[1]||String(html||'').match(/<time[^>]+datetime=["']([^"']+)["']/i)?.[1]||'';const d=Date.parse(rawDate);return{description:description.slice(0,1200),publishedAt:Number.isFinite(d)?new Date(d).toISOString().slice(0,10):dateFromText(rawDate)}}
function meaningfulDescription(v){const text=String(v||'').replace(/\s+/g,' ').trim();return text.length>=60&&text.split(/\s+/).filter(Boolean).length>=8}
function normalize(source,link){const sig=score({...link,vendor:source.vendor});return{id:`live-${source.id}-${hash(link.url)}`,vendor:source.vendor,topic:link.title,publishedAt:link.publishedAt,sourceTitle:link.title,sourceUrl:link.url,sourceType:source.kind,summary:`New item discovered from ${source.vendor}'s official source surface. Open the primary source before drafting and verify the exact product claims.`,whyItMatters:'This item matched the Creator Console research universe and is being surfaced for evidence review before it can become a post.',categories:[source.vendor,'AI / Data'],signals:{fit:sig.fit,novelty:sig.novelty,evidence:sig.evidence,teachability:sig.teachability},angleSuggestions:angleSuggestions({...link,vendor:source.vendor}),educationalPotential:sig.potential,status:'discovered-needs-evidence-review',discovery:{mode:'official-source-crawl',sourceId:source.id,sourceKind:source.kind,discoveredAt:new Date().toISOString()}}}
async function enrich(item){try{const html=await fetchText(item.sourceUrl,{timeoutMs:6500});const md=detailMetadata(html),usable=meaningfulDescription(md.description);return{...item,publishedAt:md.publishedAt||item.publishedAt,summary:usable?md.description:item.summary,status:usable?'primary-source-enriched':item.status,evidence:{sourceUrl:item.sourceUrl,sourceType:item.sourceType||'official-blog',publishedAt:md.publishedAt||item.publishedAt,excerpt:usable?md.description:null,confidence:usable?'high':'medium'},discovery:{...item.discovery,...(!usable&&md.description?{enrichmentWarning:'Primary page metadata description was too thin to qualify as evidence.'}:{})}}}catch(e){return{...item,evidence:{sourceUrl:item.sourceUrl,sourceType:item.sourceType||'official-blog',publishedAt:item.publishedAt,excerpt:null,confidence:'medium'},discovery:{...item.discovery,enrichmentError:String(e.message||e).slice(0,160)}}}}
function seedItems(){return seed.map(x=>({...x,sourceType:'official-blog',status:'verified-seed',educationalPotential:Math.round(['fit','novelty','evidence','teachability'].map(k=>Number(x.signals?.[k]||0)).reduce((a,b)=>a+b,0)/20*100),evidence:{sourceUrl:x.sourceUrl,sourceType:'official-blog',publishedAt:x.publishedAt,excerpt:x.summary,confidence:'high'},discovery:{mode:'verified-seed'}}))}
function dedupe(items){const seen=new Set(),out=[];for(const x of items){const key=(x.sourceUrl||x.url||x.topic||x.title||'').toLowerCase().replace(/\?.*$/,'').replace(/\/$/,'');if(!key||seen.has(key))continue;seen.add(key);out.push(x)}return out}
async function discover({limit=20,enrichLimit=12}={}){const results=await Promise.allSettled(SOURCES.map(async source=>({source,...await fetchSource(source)})));const raw=[],sources=[];for(let i=0;i<results.length;i++){const r=results[i],source=SOURCES[i];if(r.status==='fulfilled'){sources.push({id:source.id,vendor:source.vendor,ok:true,mode:r.value.mode,count:r.value.links.length});raw.push(...r.value.links.map(x=>normalize(source,x)))}else sources.push({id:source.id,vendor:source.vendor,ok:false,count:0,error:String(r.reason?.message||r.reason).slice(0,180)});}const ranked=dedupe(raw).sort((a,b)=>(b.educationalPotential||0)-(a.educationalPotential||0)||Date.parse(b.publishedAt||0)-Date.parse(a.publishedAt||0));const head=ranked.slice(0,Math.max(0,Math.min(20,enrichLimit))),tail=ranked.slice(head.length);const enriched=await Promise.all(head.map(enrich));const merged=dedupe([...enriched,...tail,...seedItems()]).sort((a,b)=>(b.educationalPotential||0)-(a.educationalPotential||0)||Date.parse(b.publishedAt||0)-Date.parse(a.publishedAt||0)).slice(0,Math.max(1,Math.min(50,limit)));return{schema:'creator-research-discovery/v2',generatedAt:new Date().toISOString(),sourcePolicy:'official-source-discovery-plus-primary-page-enrichment-with-verified-seed-fallback',sources,liveDiscoveryCount:raw.length,enrichedCount:enriched.filter(x=>x.status==='primary-source-enriched').length,items:merged};}
module.exports={SOURCES,TOPIC_TERMS,stripHtml,dateFromText,extractLinks,parseFeed,detailMetadata,meaningfulDescription,score,dedupe,discover};
