'use strict';
function config(){const url=process.env.SUPABASE_URL||process.env.CREATOR_SUPABASE_URL||'',key=process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.CREATOR_SUPABASE_SECRET_KEY||'';return{configured:Boolean(url&&key),url:url.replace(/\/$/,''),key}}
async function request(path,{method='GET',body,headers={}}={}){const c=config();if(!c.configured)throw Object.assign(new Error('Durable storage is not configured'),{code:'STORAGE_NOT_CONFIGURED'});const r=await fetch(`${c.url}/rest/v1/${path}`,{method,headers:{apikey:c.key,Authorization:`Bearer ${c.key}`,'Content-Type':'application/json',Prefer:'return=representation',...headers},body:body===undefined?undefined:JSON.stringify(body)});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{data=text}if(!r.ok)throw Object.assign(new Error(`Storage request failed: ${r.status}`),{code:'STORAGE_REQUEST_FAILED',status:r.status,details:data});return data}
function cleanDraft(d){return{run_id:String(d.runId||d.run_id||''),platform:String(d.platform||''),topic:String(d.topic||'').slice(0,1000),content:String(d.content||''),status:String(d.status||'draft').slice(0,80),version:Math.max(1,Number(d.version||1)),run_receipt:d.runReceipt||d.run_receipt||null,approval_receipt:d.approvalReceipt||d.approval_receipt||null}}
async function saveDraft(d){const row=cleanDraft(d);if(!row.run_id||!row.platform||!row.topic||!row.content)throw Object.assign(new Error('runId, platform, topic and content are required'),{code:'INVALID_DRAFT'});return request('creator_drafts?on_conflict=run_id,platform,version',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:row})}
async function listDrafts(limit=50){return request(`creator_drafts?select=*&order=created_at.desc&limit=${Math.max(1,Math.min(200,Number(limit||50)))}`)}
async function saveResearch(items=[]){const rows=(Array.isArray(items)?items:[]).slice(0,100).filter(x=>x?.id&&x?.sourceUrl).map(x=>({id:String(x.id),source_url:String(x.sourceUrl),vendor:String(x.vendor||''),topic:String(x.topic||x.sourceTitle||'').slice(0,1000),published_at:x.publishedAt||null,status:String(x.status||'discovered'),payload:x,updated_at:new Date().toISOString()}));if(!rows.length)return[];return request('creator_research_items?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:rows})}
async function listResearch(limit=100){return request(`creator_research_items?select=*&order=published_at.desc.nullslast,discovered_at.desc&limit=${Math.max(1,Math.min(250,Number(limit||100)))}`)}
async function saveProfile(profile={}){const row={id:'default',identity:profile.identity||{},voice:profile.voice||{},expertise:Array.isArray(profile.expertise)?profile.expertise:[],updated_at:new Date().toISOString()};return request('creator_profiles?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:row})}
async function getProfile(){const rows=await request('creator_profiles?id=eq.default&select=*');return Array.isArray(rows)&&rows.length?rows[0]:null}
async function savePublication(p={}){const row={run_id:String(p.runId||''),platform:String(p.platform||''),external_id:p.externalId||p.postId||null,draft_hash:String(p.draftHash||''),publication_receipt:p.receipt||p};return request('creator_publications',{method:'POST',body:row})}
async function listPublications(limit=50){return request(`creator_publications?select=*&order=published_at.desc&limit=${Math.max(1,Math.min(200,Number(limit||50)))}`)}
module.exports={config,request,saveDraft,listDrafts,saveResearch,listResearch,saveProfile,getProfile,savePublication,listPublications};
