'use strict';
function config(){const url=process.env.SUPABASE_URL||process.env.CREATOR_SUPABASE_URL||'',key=process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.CREATOR_SUPABASE_SECRET_KEY||'';return{configured:Boolean(url&&key),url:url.replace(/\/$/,''),key}}
async function request(path,{method='GET',body,headers={}}={}){const c=config();if(!c.configured)throw Object.assign(new Error('Durable storage is not configured'),{code:'STORAGE_NOT_CONFIGURED'});const r=await fetch(`${c.url}/rest/v1/${path}`,{method,headers:{apikey:c.key,Authorization:`Bearer ${c.key}`,'Content-Type':'application/json',Prefer:'return=representation',...headers},body:body===undefined?undefined:JSON.stringify(body)});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{data=text}if(!r.ok)throw Object.assign(new Error(`Storage request failed: ${r.status}`),{code:'STORAGE_REQUEST_FAILED',status:r.status,details:data});return data}
function cleanDraft(d){return{run_id:String(d.runId||d.run_id||''),platform:String(d.platform||''),topic:String(d.topic||'').slice(0,1000),content:String(d.content||''),status:String(d.status||'draft').slice(0,80),version:Math.max(1,Number(d.version||1)),run_receipt:d.runReceipt||d.run_receipt||null,approval_receipt:d.approvalReceipt||d.approval_receipt||null}}
async function saveDraft(d){const row=cleanDraft(d);if(!row.run_id||!row.platform||!row.topic||!row.content)throw Object.assign(new Error('runId, platform, topic and content are required'),{code:'INVALID_DRAFT'});return request('creator_drafts?on_conflict=run_id,platform,version',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:row})}
async function listDrafts(limit=50){return request(`creator_drafts?select=*&order=created_at.desc&limit=${Math.max(1,Math.min(200,Number(limit||50)))}`)}
async function saveResearch(items=[]){const rows=(Array.isArray(items)?items:[]).slice(0,100).filter(x=>x?.id&&x?.sourceUrl).map(x=>({id:String(x.id),source_url:String(x.sourceUrl),vendor:String(x.vendor||''),topic:String(x.topic||x.sourceTitle||'').slice(0,1000),published_at:x.publishedAt||null,status:String(x.status||'discovered'),payload:x,updated_at:new Date().toISOString()}));if(!rows.length)return[];return request('creator_research_items?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:rows})}
async function listResearch(limit=100){return request(`creator_research_items?select=*&order=published_at.desc.nullslast,discovered_at.desc&limit=${Math.max(1,Math.min(250,Number(limit||100)))}`)}
async function saveProfile(profile={}){const row={id:'default',identity:profile.identity||{},voice:profile.voice||{},expertise:Array.isArray(profile.expertise)?profile.expertise:[],updated_at:new Date().toISOString()};return request('creator_profiles?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:row})}
async function getProfile(){const rows=await request('creator_profiles?id=eq.default&select=*');return Array.isArray(rows)&&rows.length?rows[0]:null}
function cleanBrief(b={}){return{id:String(b.id||''),topic:String(b.topic||'').slice(0,1000),status:String(b.status||'captured').slice(0,80),mode:String(b.mode||'factual-explainer').slice(0,80),trigger:String(b.trigger||'').slice(0,4000),audience:String(b.audience||'').slice(0,1000),teaching_outcome:String(b.teachingOutcome||b.teaching_outcome||'').slice(0,2000),creator_take:String(b.creatorTake||b.creator_take||'').slice(0,6000),platforms:Array.isArray(b.platforms)?b.platforms:[],artifact_plan:b.artifactPlan||b.artifact_plan||null,warnings:Array.isArray(b.warnings)?b.warnings:[],payload:b,updated_at:new Date().toISOString()}}
async function saveBrief(b){const row=cleanBrief(b);if(!row.id||!row.topic)throw Object.assign(new Error('brief id and topic are required'),{code:'INVALID_BRIEF'});return request('creator_content_briefs?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:row})}
async function listBriefs(limit=50){return request(`creator_content_briefs?select=*&order=updated_at.desc&limit=${Math.max(1,Math.min(200,Number(limit||50)))}`)}
async function getBrief(id){const safe=encodeURIComponent(String(id||''));const rows=await request(`creator_content_briefs?id=eq.${safe}&select=*`);return Array.isArray(rows)&&rows.length?rows[0]:null}
async function saveSources(briefId,sources=[]){const rows=(Array.isArray(sources)?sources:[]).filter(x=>x?.id&&x?.url).map(s=>({id:String(s.id),brief_id:String(briefId),url:String(s.url),canonical_url:String(s.canonicalUrl||s.url),evidence_class:String(s.evidenceClass||''),title:String(s.title||'').slice(0,500),publisher:String(s.publisher||'').slice(0,300),published_at:s.publishedAt||null,captured_at:s.capturedAt||new Date().toISOString(),snapshot_hash:s.snapshotHash||null,user_note:String(s.userNote||'').slice(0,4000),resolution_status:String(s.resolutionStatus||'resolved'),payload:s}));if(!rows.length)return[];return request('creator_sources?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:rows})}
async function listSources(briefId){return request(`creator_sources?brief_id=eq.${encodeURIComponent(String(briefId||''))}&select=*&order=captured_at.asc`)}
async function saveClaims(briefId,claims=[]){const rows=(Array.isArray(claims)?claims:[]).filter(x=>x?.id&&x?.text).map(c=>({id:String(c.id),brief_id:String(briefId),claim_text:String(c.text),claim_type:String(c.claimType||'fact'),status:String(c.status||'unresolved'),confidence:String(c.confidence||'unknown'),supporting_source_ids:Array.isArray(c.supportingSourceIds)?c.supportingSourceIds:[],caveat:String(c.caveat||'').slice(0,3000),payload:c,updated_at:new Date().toISOString()}));if(!rows.length)return[];return request('creator_claims?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:rows})}
async function listClaims(briefId){return request(`creator_claims?brief_id=eq.${encodeURIComponent(String(briefId||''))}&select=*&order=created_at.asc`)}
async function savePublication(p={}){const row={run_id:String(p.runId||''),platform:String(p.platform||''),external_id:p.externalId||p.postId||null,draft_hash:String(p.draftHash||''),publication_receipt:p.receipt||p};return request('creator_publications',{method:'POST',body:row})}
async function listPublications(limit=50){return request(`creator_publications?select=*&order=published_at.desc&limit=${Math.max(1,Math.min(200,Number(limit||50)))}`)}
module.exports={config,request,saveDraft,listDrafts,saveResearch,listResearch,saveProfile,getProfile,saveBrief,listBriefs,getBrief,saveSources,listSources,saveClaims,listClaims,savePublication,listPublications};
